### ISSUE TITLE
How can I run the experiment of “SAT vs Table Position Embeddings”？

### ISSUE THREAD

**Issue by YaooXu** [zhhongzhi/sat#1]
I am interested in your work about comparing the table position encoding with SAT.

But I don't find the code about this part in your repository, would you mind adding code of this part to the repository？

Thanks a lot 😄

**Comment by zhhongzhi** [comment]
OK, I could add  it at this weekend (or later).

**Comment by zhhongzhi** [comment]
I have added the code into "ablation" folder. 
Reopen this issue if you have any problem on running the script.
