### ISSUE TITLE
function  build_vmm makes the code very slow

### ISSUE THREAD

**Issue by ziweiji** [zhhongzhi/sat#2]
I run your code but it is too slow to train and get results. I think it is due to function **build_vmm** . Do you have any advice about this problem?

**Comment by zhhongzhi** [comment]
How slow it is? Generally, it should take 1 hour per epoch with V100.

**Comment by zhhongzhi** [comment]
![image](https://user-images.githubusercontent.com/17524796/118282511-eca81d00-b500-11eb-8506-56b02ed24bc9.png)
More workers may helps but large memory would it takes.
